### ISSUE TITLE
No tray icon in KDE 5.8

### ISSUE THREAD

**Issue by tsurrel** [elboulangero/goodvibes#28]
On ArchLinux with KDE, I don't have a tray icon for Goodvibes, which leads to the weird situation where, if I click on File>Close UI, I don't have any access to Goodvibes interface anymore !

**Comment by elboulangero** [comment]
Well it's actually the expected behavior.

Goodvibes doesn't use the "AppIndicator" stuff, so it won't display any tray icon.

When the UI is closed, it's a kind of daemon mode, so Goodvibes disappears. You can bring it back different ways. Either you invoke it on the command line (just type `goodvibes`). Another way is click on the media indicator provided by your desktop. Goodvibes should appear there, and maybe you can bring it in front this way. It depends on how the media indicator works on KDE.

**Comment by tsurrel** [comment]
Ok thank you for the explanation. The result is a bit unusual in KDE (I have to right click on the media player tray icon and then click on 'Open'). It doesn't provide a way to chose a station without re-opening the goodvibes UI either.

But thanks for the nice app ! I'm looking forward an easy way to add stations (http://www.radiofrance.fr/sites/default/files/pages_uploaded_files/radio_france_-_adresses_flux_mp3_-_decembre_2016.pdf), maybe I will help if I have a bit of time !

**Comment by elboulangero** [comment]
> The result is a bit unusual in KDE (I have to right click on the media player tray icon and then click on 'Open').

Yep I can only agree that it's a bit unusual, sorry about that :) But on the other hand, there's no obligation to click on "Close UI", so anyone who want an usual behavior just stays away from this devil "Close UI" :)

> It doesn't provide a way to chose a station without re-opening the goodvibes UI either.

Yep most of the media indicators I've seen up to now show the station list. KDE is maybe the only one which doesn't do it. Maybe it's on their TODO list.

> (http://www.radiofrance.fr/sites/default/files/pages_uploaded_files/radio_france_-_adresses_flux_mp3_-_decembre_2016.pdf)

Good link, thx !
