### ISSUE TITLE
Add an "add" button for stations

### ISSUE THREAD

**Issue by hadware** [elboulangero/goodvibes#31]
Au préalable, génial comme travail ce petit outils, surtout sur la documentation et le packaging qui sont de qualitay.

Small detail though: i'm a decently computer-savvy, but it took be a bit of time that, to add a station, you had to right click *on the stations lists* and then ionly I could find the 'add station'.
I don't think this is very intuitive, and a simple "+" button in the top bar would probably fix that quickly.

**Comment by elboulangero** [comment]
Hi @hadware,

thx for the feedback. I'm not so keen on adding an 'Add' button, because then I should also add a 'Remove' button and an 'Edit' button. And then I'll find myself duplicating these 3 commands, which I find a pity.

On the other hand, you're not the first one that didn't find the way at a first glance, and I agree it's not immediately obvious how to manage stations...

I'll think about it...

**Comment by sebas22** [comment]
And what about add a menu Radio in the menu bar ?
You could then add the 3 items (add/edit/delete), and you probably will be able to use the same events than the ones triggered by the context-menu, won't you ?
Additionally, the menu can host in the future other actions that may happen to be necessary, no ?

**Comment by sebas22** [comment]
And what about adding a menu Radio in the menu bar ?
You could then add it the 3 items (add/edit/delete), and you probably will be able to use the same events than the ones triggered by the context-menu, won't you ?
Additionally, the menu can host in the future other actions that may happen to be necessary, no ?

**Comment by elboulangero** [comment]
Alright, after a bit of using I also suddenly felt that "Add Station..." was missing somewhere, I just added it in the main menu.

However, I don't want to add "Edit Station" or "Remove Station". The reason is that when you click on a station, the station is not only *selected*, it's also *played*. So using "Edit" or "Remove" from another place than the right-click context menu would be inconvenient anyway: you would click a station, swear because it starts playing, stop the playback, then click on the menu, then select "Edit". Very frustrating.

Furthermore, if it's true that having "Add Station" in the right-click context menu is not intuitive, it's not true for "Edit" or "Remove". I think most of the users will naturally right-click if they want to edit a station.

Settled for now.
