### ISSUE TITLE
'com.elboulangero.Goodvibes.Core' is not installed

### ISSUE THREAD

**Issue by tbigot** [elboulangero/goodvibes#34]
Compiling from git, I get this error message when trying to launch:

`[GLib-GIO] Settings schema 'com.elboulangero.Goodvibes.Core' is not installed`

It used to work with release 0.1.

**Comment by elboulangero** [comment]
Yep, this is due to the fact that, from version 0.2, I use [GSettings](https://developer.gnome.org/GSettings/) to handle preferences.

GSettings is nice and all, but makes it a bit tricky for people hacking around, because it expects to have the schema files installed. So you have two solutions here.

**Solution 1**. Tell explicitly to GSettings where the schema file is installed.

    export GSETTINGS_SCHEMA_DIR=data
    ./src/goodvibes

**Solution 2** Install Goodvibes, then GSettings will find the schema file installed in the expected location, and everything will be fine. So basically:

    sudo make install

This is all documented in the file `HACKING.md`.

I don't know of a better solution at the moment...

**Comment by tbigot** [comment]
Thanks, but I *did* install it. In my user directory (`prefix` = my home). ;-)
This was my first attempt when I got this error. So is there a way to install it in a non system dir and use it without exporting any variable?

**Comment by elboulangero** [comment]
I don't think so.

GSettings looks for the schema file in the usual directories, which are at least `/usr/share/glib-2.0/schemas` and  `/usr/local/share/glib-2.0/schemas`. Maybe more directories are checked, but I'm not sure.

So if you decide to install somewhere else, you must set the `GSETTINGS_SCHEMA_DIR` variable, which is annoying I agree.

I'm quite new to this GSettings thing, so I don't know all the subtleties yet. There might be a better way to handle this situation, but I don't know it.

**Comment by tbigot** [comment]
The `GSETTINGS_SCHEMA_DIR` trick works fine when launching goodvibes from the src directory. But when installed to a user dir, it does not seem sufficient:
```sh
GSETTINGS_SCHEMA_DIR=/home/tbigot/share/glib-2.0/schemas/ goodvibes
**
ERROR:ui/gv-ui-helpers.c:39:gv_builder_load: 'file_found' should not be NULL
Abandon (core dumped)
```

Is there any other variable to set? I haven’t found anything relevant in `HACKING.md`

**Comment by elboulangero** [comment]
Well, now this is another error: the ui files are not found.

Ui files are searched according to the XDG data directories. By default it's `/usr/local/share/` and `/usr/share/`. On top of that, we also look in the current data directory, so that launching Goodvibes from the development directory works. The line that does this magic trick can be found in `src/ui/gv-ui-helpers.c`.

    /* Find the location of the ui file */
    file_found = gv_get_first_existing_path(GV_DIR_CURRENT_DATA | GV_DIR_SYSTEM_DATA, ui_filename);

Ok, so what you want to do is to play with the XDG directories. There's a variable for that: `XDG_DATA_DIRS`. Depending on your system, this variable may or may not be defined.

    printenv | grep XDG_DATA_DIRS

If this variable **is not** defined, the default xdg data dirs are used. That's to say `/usr/local/share/` and `/usr/share/`. If this variable **is** defined, then **only** the paths in this variable are searched.

So you can try defining this variable to something like that.

    export XDG_DATA_DIRS=/home/tbigot/share/

I'm not sure it will work though, because any shared resource that don't belong to Goodvibes, and therefore is not in your custom share directory, won't be found. I think it's safer to do that:

    export XDG_DATA_DIRS=/home/tbigot/share/:/usr/local/share/:/usr/share/

Or, if you found that XDG_DATA_DIRS is already defined on your system when you tried the `printenv` command above, then you should do something like that:

    export XDG_DATA_DIRS=/home/tbigot/share/:$XDG_DATA_DIRS

As you can see, it's not so obvious...

Btw, the `XDG_DATA_DIRS` variable is also used to find the schema files, so when you will manage to configure `XDG_DATA_DIRS` properly, you should not need to export `GSETTINGS_SCHEMA_DIR` anymore.

Please confirm that all that stuff works. Cheers :)

**Comment by tbigot** [comment]
```sh
export XDG_DATA_DIRS=/home/tbigot/share/:$XDG_DATA_DIRS
```
seems to do the job. I have no schema nor ui missing files complaints anymore. But I have this:
```sh
ERR  15:39:07 [GLib-GIO] Settings schema 'com.elboulangero.Goodvibes.Core' does not contain a key named 'pipeline-enabled'
```
which I think is not the same issue.

Thanks anyway.
Cheers

**Comment by elboulangero** [comment]
This pipeline thing was added a few days ago. Such a message shows that somehow, the schema file picked up is not the latest one from the source code, or something like that.

The schema source file is `data/com.elboulangero.Goodvibes.gschema.xml.in`. It is then transformed into `data/com.elboulangero.Goodvibes.gschema.xml` by the script `./configure`. If the source was updated, the other file won't be rebuild automatically, you have to run `./configure` manually. Compare the date between the two files, or compare them with `meld` or similar.

Then, the file actually used when you launch Goodvibes will be `gschema.compiled`. This file is automatically rebuild if needed when you type `make`, and when you install, it's also rebuild in the target directory, where schemas are installed.

**Comment by tbigot** [comment]
As a regular CMake user, I forget sometimes re-running `./configure` is mandatory!
Thanks _Beauf_, it works perfectly. ;-)

**Comment by elboulangero** [comment]
Alright !

I will add a line in the `HACKING.md` regarding install in a non-standard directory. So if I understand properly, the procedure you follow to install in `/home/user/goovibes` (for example) is:

- At compile-time: `./configure --prefix=/home/user/goovibes`
- At run-time: `export XDG_DATA_DIRS=/home/user/goovibes`

Is that all there is to know ?

*Beauf de France*

**Comment by tbigot** [comment]
That’s it. Tested on a fresh install just now, and it works like a charm.
