### ISSUE TITLE
Send commands via command line

### ISSUE THREAD

**Issue by oliverpool** [elboulangero/goodvibes#35]
Is there any way to send commands via the CLI like:
```
goodvibes --do=play
goodvibes --do=stop
goodvibes --do=toggle
goodvibes --do=previous
goodvibes --do=next
...
```
I couldn't find anything in the `--help-all`

I would like to have my own keybindings, and to do that I just need to bind a key with a such a command.

**Comment by elboulangero** [comment]
Goodvibes exposes 2 names on D-Bus. For example, assuming that you have `qdbus` installed:

    qdbus | grep Goodvibes
     com.elboulangero.Goodvibes
     org.mpris.MediaPlayer2.Goodvibes

You can use these two entry points to send commands to Goodvibes, and access properties, and even watch for signals being emitted.

Using this from the shell is, however, a bit tedious, that's why Goodvibes comes with a command-line client to ease these tasks.

    goodvibes-client

And I guess this is what you're looking for.

The client is mostly a wrapper around the D-Bus interface exposed at `com.elboulangero.Goodvibes`. It means that, if ever you play with the settings and disable what is called the *Native D-Bus Server* in the preferences window, the client doesn't work anymore.

**Comment by oliverpool** [comment]
Thank you for your quick reply!

The `goodvibes-client launch` command fails with `DBus call error: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program com.elboulangero.Goodvibes: No such file or directory` (on Linux 4.9.6-1-ARCHLINUX)

The other commands seem to work fine (once goodvibes is running).

Maybe you could include this in the `--help` section:
```
To control goodvibes via the command line, see the goodvibes-client executable
```

**Comment by elboulangero** [comment]
Yep good idea, I'll do that.

Indeed launching fails at the moment, I'm trying to find my way in the mess of dbus service files, desktop files, GApplication, D-Bus and all these things, and it's really a mess, or maybe I'm just dumb. Hopefully I'll release something that works in a 0.2.1 pretty soon.

**Comment by elboulangero** [comment]
Ok I was just dumb, I think I got it right now !
