### ISSUE TITLE
Goodvibes shouldn't exit after pressing close button while playing on Ubuntu

### ISSUE THREAD

**Issue by khurshid-alam** [elboulangero/goodvibes#42]
Current Scenario:

1. Start playing
2. Click on close button.

Result:
Goodvibes exits and quit playing.

Expected Result:
Instead it should have minimized to sound-menu and keep playing music.

That's how many other music players (Rhythmbox, Gradio..etc) works on Ubuntu. 

If users first **pause it and then press close-button**, then only it should exit completely. 

Thanks.

**Comment by khurshid-alam** [comment]
I can work-around the issue if I launch it with `-b --without-ui` from terminal. But I still need the gui to add/edit station. So that doesn't really solve the problem.

**Comment by elboulangero** [comment]
If you want to get rid of the user interface, but keep the app running, you can click on "Close UI" in the main menu.

**Comment by elboulangero** [comment]
It seems to me very normal and standard that an application quits when you click on the close button. It's been like that forever since the close button was invented.

Usually, the only applications that don't respect this rule are the applications that come with a system tray icon.

I did a bit of tests on Ubuntu with different media players.
- Applications that exit: Totem, Vlc, Audacious, Quodlibet
- Applications that vanish in the background: Rhythmbox

So Rhythmbox is the exception rather than the rule here.

As I said in the comment above, Goodvibes also provide this weird behavior of vanishing rather than exiting, by clicking on "**Close UI**" in the main menu. It's true that this behavior is convenient, as long as there's a status icon somewhere (in Ubuntu, it's the sound menu) that allows to easily bring back the application.

It's convenient for some usages, but not all of them, and not everybody wants to see their player disappearing while still playing music. If you're not running Ubuntu, if you have no sound menu, how do you bring back the UI ? It's not obvious to everybody that they have to launch the app again, stop the music, then close. Or to understand that the close button behave differently than clicking on "File -> Close". Or to understand that the close button behaves differently depending if music is playing or not. There's nothing obvious with this behavior.

So sorry, but I'll stay away from that. The close button will remain a good old, unsurprising close button, one that quits the application.

**Comment by khurshid-alam** [comment]
Fair enough. Yes **close-ui** works for me. Only if I could bind a keyboard shortcut to `close ui`. It is certainly possible with Compiz-config-settings-manager.  But I rather want a inbuilt option. Thoughts?

Thanks.

**Comment by elboulangero** [comment]
You mean to bind a keyboard shortcut to that command ? That's fairly easy. For example, 'Echap' is already bound to minimizing, so I could bind another shortcut to 'Close UI' I guess.

**Comment by elboulangero** [comment]
I can also add these "Accelerators" or whatever the name, I don't remember, so that you can hit 'Alt' to expand the menu, and then a letter to execute a command.

**Comment by elboulangero** [comment]
Keyboard shortcuts implemented in 20e0cc31a281c244c6116e598394cb114cbb67f1.
