### ISSUE TITLE
Goodvibes station and Media Player station disagree

### ISSUE THREAD

**Issue by dln949** [elboulangero/goodvibes#76]
Ubuntu 17.10 (x11), gnome 3.26.2, Goodvibes 0.3.4.  Also running the TopIcons Plus extension.  

Run Goodvibes --status-icon.  That makes Goodvibes appear in the top bar.  

From Goodvibes icon in the top bar, start a station.  Then, look in the gnome media player in the top bar tray, it will show the same station, song, etc. playing.  

Then, again from the Goodvibes icon in the top bar, change to a different station.  If you then look in the gnome media player in the top bar tray, you will see the correct track title, but the wrong station.  

Also - Completely within the gnome media player in the top bar tray, if you are playing a station, and then within the Goodvibes playlist shown in the gnome media player in the top bar tray you expand the playlist and select a different station, the track title correctly changes in the gnome media player in the top bar tray, but the station title does not change.

**Comment by elboulangero** [comment]
Hey, thanks for the feedback I will have a look.

**Comment by elboulangero** [comment]
I can't really reproduce your issue on GNOME. I realize that you're running Ubuntu, so your GNOME top bar must be quite different from mine. For example, m gnome media player does not have any playlist.

Here are a few screenshots on my side

![screenshot from 2018-03-03 22-22-51](https://user-images.githubusercontent.com/1942580/36936336-a198de52-1f36-11e8-8c0f-180934434918.png)
Here's my everyday: the radion station doesn't publish any metadata, so I get nothng.

![screenshot from 2018-03-03 22-23-10](https://user-images.githubusercontent.com/1942580/36936344-c5466e28-1f36-11e8-83eb-c8cb9d9a7100.png)
This radio decides to fill the "title' metadata with the radio name. Better than nothing.

![screenshot from 2018-03-03 22-23-39](https://user-images.githubusercontent.com/1942580/36936349-e01b552e-1f36-11e8-99cb-90dc00dbd3aa.png)
This radio put both artist and title in the 'title' metadata. That's a common case.

Anyway, Goodvibes and the GNOME media player always agree.

Can you send me the url of the stations you listen to when you see this issue ? Thx !

**Comment by dln949** [comment]
Thanks, I will provide you the requested URLs, and some screenshots, but it might be a couple days before I can take the time to do that.  (From your response I can tell that you are not understanding the issue I am trying to describe - not a criticism of you, I knew it would be difficult for me to describe.  That is why I want to add some screenshots.)

**Comment by dln949** [comment]
I have attached six jpg screenshot files to this message:  In screenshots 1a.jpg - 3a.jpg, I am listening to "Joe Willis....." on "DI Classic Trance" (found at di.fm).  You will notice that in all three screenshots they  correctly display "Joe Willis....".  However, in screenshot 2a.jpg, the station "DI Classic Trance" is replaced by "Unknown"; and, in screenshot 3a.jpg, a completely incorrect station of "DI Club Dubstep" is displayed.  

I then changed the station to "AH.FM" (found at ah.fm), listening to "Chris Copper...."  You will notice the same kind of problems:  1a.jpg displays as expected; 2a.jpg displays the correct show, but "Unknown" for the station; and 3a.jpg displays the correct show, but the incorrect station (still "stuck" at displaying "DI Club Dubstep").  

![1a](https://user-images.githubusercontent.com/8601150/36947781-3d5d0afc-1f96-11e8-8324-3b5e26831822.jpg)
![2a](https://user-images.githubusercontent.com/8601150/36947782-3d747098-1f96-11e8-854c-7a7ba2a6b8e0.jpg)
![3a](https://user-images.githubusercontent.com/8601150/36947783-3d86cd9c-1f96-11e8-8f5e-b444c2a2c507.jpg)
![4a](https://user-images.githubusercontent.com/8601150/36947784-3d9e93dc-1f96-11e8-9070-755047f16046.jpg)
![5a](https://user-images.githubusercontent.com/8601150/36947785-3db205b6-1f96-11e8-8e0a-6dd7c09ff03c.jpg)
![6a](https://user-images.githubusercontent.com/8601150/36947786-3dda59ee-1f96-11e8-987e-a048422ef3aa.jpg)

**Comment by elboulangero** [comment]
Thanks for the details ! Let me explain you what's going on here...

#### Introduction

First, Goodvibes communicates with the **GNOME Panel** (in the middle of the screen) and the **Ubuntu Menu** (to the right) using a protocol named MPRIS2. Goodvibes actually just sends *signals*. Ubuntu and GNOME catch these signals, and do whatever they want with it.

If you want to see that by yourself, open a terminal while Goodvibes is running, and run this command.

    gdbus monitor --session --dest org.mpris.MediaPlayer2.Goodvibes

When the *metadata* of the station you're listening to changes, you will see this kind of message psasing by.

    /org/mpris/MediaPlayer2: org.freedesktop.DBus.Properties.PropertiesChanged ('org.mpris.MediaPlayer2.Player', {'Metadata': <{'mpris:trackid': <objectpath '/com/elboulangero/Goodvibes/TrackList/0x564b231643a0'>, 'goodvibes:station': <'Lamax Radio'>, 'xesam:url': <'http://lamaxradio.ice.infomaniak.ch/la-max-radio-128.mp3'>, 'xesam:title': <'Chameleon, Pnau'>}>}, @as [])

If you want more details about the metadata sent over the MPRIS spec, have a look at <https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/>.

#### First issue: radio stations don't fill their metadata properly

The first thing you want to notice in the example above is that there is the field `'xesam:title': <'Chameleon, Pnau'>`, and there is NO field `'xesam:artist'`.

The field `xesam:title` is filled by Goodvibes with what is provided by the radio station. As you can see here, it contains both the artist and the title. And on the other hand, there's no field `xesam:artist`, because the audio stream does not contain a metadata tag `artist`.

If you try that with a few radio stations, you will see that most, maybe even all of the radio stations, do that. They put all the information in the field "title", and they don't fill the field "artist", or "album", or any other field.

Too bad, Goodvibes can't do anything about that. We just forward that through the MPRIS protocol, and GNOME and Ubuntu do whatever they want with it.

Therefore you end up with 2a.jpg and 5a.jpg The field "artist" is left to "Unknown", and the field "title" contains both artist and title.

For the scrennshots 3a.jpg and 6a.jpg, there is the same problem, the difference is that Ubuntu does not write "Artist: unknown" if there is no artist: it doesn't display anything. So you just have one line with the title. Now if you try to listen to some audio files on your computer with an application like Rhythmbox (I see the icon on your screenshot), I'm almost sure that you will notice that artist and titles are displayed on two different lines, rather than one line.

#### Second issue: the MPRIS2 specs is not perfect

Second issue is that, if you visit the link I provided above, you will see that the MPRIS2 specification does not offer a field to pass the radio station name. And that's why you will notice `'goodvibes:station': <'Lamax Radio'>` on your terminal: Goodvibes pass the station name in a custom field that is not defined by the spec.

Now GNOME and Ubuntu can do whatever they want with this custom field, but very likely, they just ignore it. That's what happens in 2a.jpg and 5a.jpg - it is not displayed.

Additionally to this metadata field, Goodvibes pass the station name through the Playlist interface of MPRIS2, and when you change a station you can see that:

    /org/mpris/MediaPlayer2: org.freedesktop.DBus.Properties.PropertiesChanged ('org.mpris.MediaPlayer2.Playlists', {'PlaylistChanged': <(objectpath '/com/elboulangero/Goodvibes/Playlist/0x55c024baca10', 'Radio Grenouille', '')>}, @as [])

This can be used by GNOME and Ubuntu, but only if they implement the Playlist interface. As far as I know, the GNOME Panel does not implement this interface, so there is no chance it does anything with that.

For Ubuntu, I don't know. Actually I have no idea why you have this `DI Club Dubstep` displayed in screenshot 3a.jpg and 6a.jpg. Are you sure that this is due to Goodvibes ? Maybe you listened to this radio with another application before, and this is a leftover that the Ubuntu Menu didn't clean up, and for some reason (bug?), it just leaves the field like this without resetting it.

**Comment by dln949** [comment]
Thank you very much for the explanation.  I appreciate the effort you put into this.  

(For the Ubuntu menu, I have not been able to figure out what makes an entry appear versus (possibly) being a "leftover" entry from a previous selection.  So far I have not noticed consistent behavior from my perspective.)
